app = "dangote-cms-frontend"
primary_region = "jnb"

[build]
  dockerfile = "frontend/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 150

[[http_service.checks]]
  grace_period = "15s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/"